name: S3 Deploy

on:
 push:
   branches:
     - main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-1

    steps:
        - uses: actions/checkout@v1
        - name: Use Node.js 
          uses: actions/setup-node@v1
          with:
            node-version: 16.16
        

        - name: Install dependencies
          run: yarn

        - name: Build
          run: yarn build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: ./
            bucket: braga.co.id
            dist-id: ESN7D10ZHJQZK
            invalidation: / *
