name: S3 Deploy

on:
 push:
   branches:
     - main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-1
      
    steps:
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
        
        - name: Run a multi-line script
          run: |
           npm install
           npm run build
           
        - name: Sync S3
           run: aws s3 sync ./ s3://braga.co.id
           
        - name: Invalidate CloudFront
          uses: chetan/invalidate-cloudfront-action@v2
          env:
           DISTRIBUTION: ESN7D10ZHJQZK
           PATHS: "/index.html"
           AWS_REGION: "ap-southeast-1"
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
