--- 
env: 
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_REGION: ap-southeast-1
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  SOURCE_DIR: build
jobs: 
  build: 
    runs-on: ubuntu-latest
name: "S3 Deploy"
steps: 
  - 
    uses: actions/checkout@v1
  - 
    name: "Use Node.js ${{ matrix.node-version }}"
    uses: actions/setup-node@v1
    with: 
      node-version: "${{ matrix.node-version }}"
  - 
    name: "Install dependencies"
    run: yarn
  - 
    name: Build
    run: "yarn build"
  - 
    name: Deploy
    uses: lbertenasco/s3-deploy@v1
    with: 
      bucket: braga.co.id
      dist-id: ESN7D10ZHJQZK
      folder: build
      invalidation: "/ *"
strategy: 
  matrix: 
    node-version: 
      - 16.16
true: 
  push: 
    branches: 
      - main
